Advance functionality
gzdwsu/RaiderSMA pull request #21
Opened 2020-02-19 01:59 UTC by MMercer8989

I have fixed previous issues with the Bracket.nextRound() method as well as problems associated with it. To correct the problems I have made alterations to Main.java, Bracket.java, Match.java, and Model.java. Each of these alterations tie together and work as I believe they were intended, more or less (this was difficult to determine sometimes as there was no clear documentation). The only noticeable change to the user would be the removal of the "ADVANCE" command as well as the removal of a parameter to "UPDATE-MATCH". these changes were made primarily to avoid user error which could effect nextRound().

2020-03-02 18:56 UTC, mikeknows commented
Merge conflict after accepting logging class PR.

<<<<<<< advance-functionality-test-branch
=======
                    case "ADVANCE":
                    	log.writeActionlog("Command Entered: " +args.get(0));
                        Model.advanceTournament();
                        return;
>>>>>>> master

2020-03-08 20:09 UTC, MMercer8989 commented
I have resolved the listed merge conflicts and re-merged. Sorry for just now getting to this, I didn't see your email until recently.

2020-03-14 13:00 UTC, mikeknows requested changes
Another conflict after accepting a PR

2020-03-14 13:00 UTC, mikeknows commented on src/wrestlingtournamentcli/Main.java
> -}
I need to be able to easily see the changes made. It appears that you deleted the original Main.java, and copied in yours with the changes you made. Please stay in the IDE when making changes.

2020-03-15 23:56 UTC, MMercer8989 commented on src/wrestlingtournamentcli/Main.java
> -}
I'm not sure why it's indicating that main is causing a conflict, to my knowledge I hadn't made any changes of this scale; when I go to resolve conflicts both segments of code appear to be the same. Will you be having regular office hours this week?

2020-03-16 20:30 UTC, MMercer8989 commented
I have changed it this time by switching case 7 to be case 6, making sure to change any necessary pieces of code that this could effect within. This was the only real difference I noticed so I'm still not sure why the entire main class was causing a conflict.

2020-03-20 16:31 UTC, mikeknows commented
Another merge conflict

2020-03-21 21:52 UTC, merged