Added Soccer Team Management Functionality
gzdwsu/RaiderSMA pull request #22
Opened 2020-02-19 22:00 UTC by codyfrancis

Adds the ability for the user to manage team and player information related
to soccer players.  Modifies the Model class to allow for either a wrestling
or soccer model to be created.  This allows for the reuse of some already
implemented code.

This code increases the capabilities of the application.  With further
development, more functionality will be given to the soccer management
portion.  This will open up the application to be used for multiple sports,
making it a more robust product.

Resolves: #12

2020-03-02 18:58 UTC, mikeknows commented
Merge conflict
public static void main(String[] args) {
	Scanner s = new Scanner(System.in);
	System.out.println("Please enter the sport you would like to manage(wrestling/soccer):");
	while(true) {
	String sportSelection = s.nextLine();
	switch(sportSelection.toLowerCase()) {
	case "wrestling":
		Model wrestlerModel = new Model("wrestling");
		wrestlingMenu();
		break;
    case "soccer":
    	Model soccerModel = new Model("soccer");
    	soccerMenu();
    	break;
    default:	
    	System.out.println("Incorrect input. Please enter wrestling/soccer");   
				}

2020-03-14 13:01 UTC, mikeknows reviewed
Another merge conflict. 

Press 'resolve conflicts' below to see where the conflict is.

2020-03-14 13:01 UTC, mikeknows commented on src/wrestlingtournamentcli/Main.java
> -}
Deleted original Main.java and pasted in your edited version.

2020-03-14 17:59 UTC, codyfrancis commented on src/wrestlingtournamentcli/Main.java
> -}
Every time I try to modify Main.java with and resubmit it my repository to show the individual changes I made, it shows that I have changed the entire file on my pull request.  Do I need to make another pull request?

2020-03-20 16:31 UTC, mikeknows requested changes
Still cannot see diff for main.java, also another merge conflict

2020-03-20 16:31 UTC, mikeknows commented on src/wrestlingtournamentcli/Main.java
> -}
If you started in eclipse with the original file and only made modifications, it would show the correct diff. It appears it has been deleted and copy pasted in. Yes, please make a new PR.

2020-03-20 17:19 UTC, closed without merging